---
- name: CCNA Lab tasks
  hosts: routers
  connection: local
  gather_facts: false
  
  vars_files:
  - vars.yml

  tasks:
    - name: 2 command configurations
      ios_command:
        commands:
          - conf t
          - "{{ item.command_1 }}"
          - "{{ item.command_2 }}"
      with_items:
      - "{{ commands }}"