---
- name: CCNA Lab tasks
  hosts: routers
  connection: local
  remote_user: "{{ username }}"
  vars:
    ansible_become_pass: "{{ password }}"
  gather_facts: false
  
  vars_files:
  - vars.yml

  tasks:
    - name: global config settings
      ios_command:
        commands:
          - conf t
          - "{{ item.command_1 }}"
          - "{{ item.command_2 }}"
      with_items:
      - "{{ commands }}"
