---
- name: CCNA Lab tasks
  hosts: routers
  connection: local
  gather_facts: false
  
  vars_files:
  - vars

  tasks:
    - name: Global config settings
      ios_command:
        commands:
          - conf t
          - {{ command_1 }}
          - {{ command_2 }}
