---
- name: Obtaining Switch Information
  hosts: switches
  connection: local
  gather_facts: False

  tasks:
    - name: Get info from switches
      ios_command:
        commands:
          - sh processes cpu history
          - sh ip int br
          - sh int status
      register: sys_output

    - debug: var=hostvars["{{ item }}"].sys_output.stdout_lines
      with_items: "{{ groups['switches'] }}"

    - name: Register switch outputs with variable
      add_host:
        name: "{{ item }}" 
        p_cpu_history: " ------------ MANDY {{ item }} Processes CPU History: ------------ \n \n {{ hostvars[item].sys_output.stdout_lines[0] | join('\n') }}"
        ip_int_br: " \n ------------ MANDY {{ item }} IP Interface Brief: ------------ \n \n {{ hostvars[item].sys_output.stdout_lines[1] | join('\n') }}"
        int_status: " \n ------------ MANDY {{ item }} Interface Status: ------------ \n \n {{ hostvars[item].sys_output.stdout_lines[2] | join('\n') }}"
      with_items: "{{ groups['switches'] }}"

    - debug: var=hostvars["{{ item }}"]['p_cpu_history']
      with_items: "{{ groups['switches'] }}"

- hosts: localhost
  connection: local
  gather_facts: False
 
  vars_files:
  - vars.yml
  
  tasks:
    - name: Switch Outputs
      cisco_spark:
        recipient_type: roomId
        recipient_id: "{{ recipient_id }}"
        personal_token: "{{ personal_token }}"
        message_type: text
        message: " {{ hostvars[item]['p_cpu_history'] }} , {{ hostvars[item]['ip_int_br'] }}, {{ hostvars[item]['int_status'] }} | join('\n \n \n') "
      with_items: "{{ groups['switches'] }}"
