---
- name: Check if any part is down
  hosts: switches
  connection: local
  gather_facts: no
  
  vars_files:
    - credentials.yml

  tasks:
    - name: obtain date
      ios_command:
        commands:
          - sh clock
      register: datetime

    - name: obtain logs
      ios_command:
        commands:
          - " sh log | include Jul  6 | down" 
      register: switch_log

    - debug: var=switch_log.stdout_lines[0]

    - debug:
        msg: "{% if switch_log.stdout_lines[0][0] == '' %} No log for today! {% else %} {{switch_log.stdout_lines[0] | join('\n')}} {% endif %}"
