---
- name: CCNA Lab tasks
  hosts: routers
  connection: local
  gather_facts: false

  roles:
    - routers

  tasks:
    - name: 2 command configurations
      ios_command:
        commands:
          - conf t
          - vlan 13
          - name vLaN13